### ISSUE TITLE
Error during `make run` on CentOS 7

### ISSUE THREAD

**Issue by tjesser-ucdavis-edu** [geodynamics/selen#2]
Hi, I'm working on updating the geodynamics.org Jenkins instance, and I've run into a problem building SELEN on CentOS 7. I am able to run `autoreconf`, `configure`, and `make` successfully, but when running `make run`, I get this error message:

```
...
---> PX_REC.F90: Merging the wet & dry pixels tables
At line 60 of file ./src/px_rec.f90 (unit = 1, file = 'weta.dat')
Fortran runtime error: Bad real number in item 1 of list input
make: *** [run] Error 2
```

With some help, I was able to discover the cause. In `weta.dat`, there is this header:

```
# Command : gmtselect pxa.dat -H4 -Df -R0/360/-90/90 -A0 -JQ180/200 -Nk/s/k/s/k
# ----------------------------------------------
#  Pixels lon-lats and with increasing latitude 
#   pixel lon(deg), lat (deg), anchor, pixel #  
# ----------------------------------------------
   187.07222477146300       -78.384814749116828              157         780
   194.39064907457319       -78.214241051321380              161         801
…
```

However, in the version being built with UbuntuLTS 14.04, the `weta.dat` header looks like this:

```
 ----------------------------------------------
  Pixels lon-lats and with increasing latitude 
   pixel lon(deg), lat (deg), anchor, pixel #  
 ----------------------------------------------
   187.07222477146300       -78.384814749116828              157         780
   194.39064907457319       -78.214241051321380              161         801
…
```

There is one more header line in the CentOS version. I think this is the issue because in `src/px_rec.f90` there are lines [53-58](https://github.com/geodynamics/selen/blob/master/src/px_rec.f90#L53-L58), which seem to be for reading in the header and discarding it. Specifically, [line 55](https://github.com/geodynamics/selen/blob/master/src/px_rec.f90#L55): `do j=1, 4` seems to be an assumption about the first four lines of weta.dat.

I am not sure, but I think the extra line is created because CentOS uses a different version of GMT, version 5.1.1, compared to UbuntuLTS's 4.5.11.

Do you think this analysis is correct? Does this project support multiple versions of GMT?

Thanks

Links:
Geodynamics Jenkins Web Interface:
https://blofeld.geodynamics.org/

Workspace files of SELEN CentOS build: https://blofeld.geodynamics.org/job/SELEN/Enable_OpenMP=yes,tag_arch=64bit,tag_os=centos/ws/

Console output of SELEN CentOS build:
https://blofeld.geodynamics.org/job/SELEN/Enable_OpenMP=yes,tag_arch=64bit,tag_os=centos/9/console

**Comment by danielemelini** [comment]
Fixed in release 2.9.12
