### ISSUE TITLE
Manual describes GMT as Public Domain which is no longer true

### ISSUE THREAD

**Issue by tjesser-ucdavis-edu** [geodynamics/selen#3]
Right now, the manual mentions in multiple places that GMT is public domain. ([Github search](https://github.com/geodynamics/selen/search?utf8=%E2%9C%93&q=public+domain)) However, the [GMT webpage](https://gmt.soest.hawaii.edu/) lists the license as LGPL3+.

From what I was able to find, GMT versions 1 and 2 were indeed Public Domain. Source: https://www.soest.hawaii.edu/pwessel/papers/1991/EOS_91/eos_91.html

But the website archives show that version 3 and 4 were under the GPL 2 or 3. Source: ftp://ftp.soest.hawaii.edu/gmt/legacy/

I'm not entirely sure how to handle mentioning GMT licensing. I guess it would depend on which versions are supported for compiling against. As it is, though, the manual cannot be considered correct.

**Comment by danielemelini** [comment]
Fixed in release 2.9.12
